### ISSUE TITLE
Bracey server error 

### ISSUE THREAD

**Issue by Mohanbarman** [turbio/bracey.vim#17]
I know there is another issue opened as same as mine but After running `npm install -prefix server` 
in bracey.vim directory where it is installed I still getting this error.
here are the screenshots.
![first1](https://user-images.githubusercontent.com/35772257/71409599-38d29300-2668-11ea-81e0-76026552bc0f.png)
![first2](https://user-images.githubusercontent.com/35772257/71409626-50118080-2668-11ea-9a48-5c38eda05102.png)

**Comment by Godnyx** [comment]
Hi! I have the same problem as you. Did you found a solution?

**Comment by Mootikins** [comment]
This is what happens when you run `npm audit fix` in the server directory. If you are okay with running a vulnerabile npm package (`htmlhint`), then these steps will get it working for the time being.
1. Reinstall from scratch, deleting the old clone of the repo (or reset it to HEAD).
2. Go to the installation directory (`<plugin directory>/bracey.vim`), then to the `server` folder.
3. Run `npm install`, then `npm install htmlhint`. This will install the vulnerable version of `htmlhint`.
DO NOT run `npm audit fix`, this will update all the packages causing the vulnerability, breaking bracey.vim in the process.

I'm not familiar with node.js, but I might go look at the documentation for `htmlhint` and see if I can get this updated for the new version.
